### post 1
POST http://localhost:3333/transactions
Content-Type: application/json

{
    "title": "Freelancer",
    "amount": 1000,
    "type": "credit"
}



### Get 2
GET http://localhost:3333/teste

### Get all
GET http://localhost:3333/hello